name: Update Embeddings
on:
  workflow_dispatch:
  push:
    paths:
      - 'content/docs/**'
  pull_request:
    paths:
      - 'content/docs/**'

jobs:
  update-embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: content/docs/**

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r embeddings/requirements.txt

      - name: Update embeddings
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENV: ${{ secrets.PINECONE_ENV }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python embeddings/main.py \
            --added "${{ steps.changed-files.outputs.added_files }}" \
            --modified "${{ steps.changed-files.outputs.modified_files }}" \
            --deleted "${{ steps.changed-files.outputs.deleted_files }}"
